name: $(Year:yyyy).$(date:MM).$(date:dd).$(rev:rr)

variables:

  projectDir: 'ffooe-api.ff-steyr.at'
  iisSite: '$(projectDir)'        # declare if name of IIS Site Name differs (IIS Service to stop)
  siteFolder: '$(projectDir)'     # declare if directory of website in \wwwroot differs for deplyoment

  project: '**/$(projectDir).csproj'
  assemblyVersion: '$(Build.BuildNumber)'
  iisBackupPath: '$(iisMainPath)\backup'
  sitePath: '$(iisMainPath)\$(siteFolder)'
  zipFile: '$(build.stagingdirectory)/*.zip'

  wwwMachine: 'ffooe.ff-steyr.local' # deployment machine
  iisMainPath: '\\$(wwwMachine)\C$\inetpub\wwwroot'
  buildPlatform: 'win-x64'
  buildConfiguration: 'Release'

trigger:
  branches:
     include:
     - 'main'
  paths: 
    include: 
    - ffooe.rest.api

pool:
  name: 'JENKINS'

resources:
  repositories:
  - repository: yaml
    type: git
    name: yaml

steps:
 - template: website-deploy.yml@yaml